Updated schema, api for enhanced calendar functionality
2020SE691T2/RecessAPI pull request #64
Opened 2021-01-26 01:53 UTC by jdurelli

2021-01-26 02:12 UTC, jdurelli commented
Does this close any other issues? Should we add an issue for the general class schedule functionality changes?

2021-01-26 13:00 UTC, jonathanmcdaniel approved these changes

2021-01-26 13:35 UTC, jonathanmcdaniel requested changes
Because we are working off of a GET request, standard practice is to not have a body in a GET method because you are supposed to be requesting data, not sending it. I didnt think this was going to be an issue since we saw it work from postman, but react will not allow this request to be made.

2021-01-26 13:35 UTC, jonathanmcdaniel commented on RecessApplication/api.py
> +        year = request.data['year']
We need to change this to be a url parameter not  body data

2021-01-26 13:35 UTC, jonathanmcdaniel commented on RecessApplication/api.py
> +        week = request.data['week']
we need to change this to be a url parameter not body data

2021-01-27 16:57 UTC, jonathanmcdaniel approved these changes

2021-01-27 16:57 UTC, gateship1 approved these changes

2021-01-28 00:58 UTC, msknobloch2 approved these changes

2021-01-28 00:58 UTC, merged