Allow PATCH for Rosters. Add static ZOOM end times if not specified. …
2020SE691T2/RecessAPI pull request #82
Opened 2021-03-03 03:36 UTC by jdurelli

…Cache Student/Teacher view for performance.

2021-03-03 03:36 UTC, jdurelli commented
I can break these up into separate PRs if wanted... just sorta worked them all at once

2021-03-03 03:59 UTC, gateship1 requested changes
The PATCH seems to be replacing the roster participants with the new payload participants and not appending them to the list.

2021-03-03 20:17 UTC, jonathanmcdaniel approved these changes

2021-03-04 00:50 UTC, msknobloch2 approved these changes

2021-03-04 00:50 UTC, gateship1 approved these changes

2021-03-04 00:51 UTC, merged